# Generated by Django 3.2.5 on 2022-02-26 18:07

from django.db import migrations, models
import trabify_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('trabify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='posts/default.png', upload_to=trabify_app.models.upload_to, verbose_name='Image'),
        ),
    ]
